# See docs.getsentry.com/on-premise/server/ for full instructions

version: '2'

services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: '@8u)20kxi2%iu(55ecz#2o*hxc4epv5*pux!h)e^&k5bc%-cyq'
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    volumes:
      - /data/sentry

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - /data/postgres

  web:
    extends: base
#    command: run web
    links:
      - redis
      - postgres
      - memcached
    depends_on:
      - worker
      - cron
    ports:
      - 9000:9000

  cron:
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached

  worker:
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
