# See docs.getsentry.com/on-premise/server/ for full instructions

version: '2'

services:
  memcached:
    restart: always
    image: memcached:1.4

  redis:
    restart: always
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - /data/postgres

  web:
    image: 447888000816.dkr.ecr.us-east-1.amazonaws.com/sentry
    restart: always
    links:
      - redis
      - postgres
      - memcached
    ports:
      - 9000:9000
    environment:
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_USE_SSL: 1
    volumes:
      - /data/sentry
    env_file:
      - ./env
    depends_on:
      - memcached
      - redis
      - postgres
      - worker
      - cron

  cron:
    command: run cron
    restart: always
    image: 447888000816.dkr.ecr.us-east-1.amazonaws.com/sentry
    links:
      - redis
      - postgres
      - memcached
    environment:
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    env_file:
      - ./env
    volumes:
      - /data/sentry
    depends_on:
      - postgres
      - redis
      - memcached

  worker:
    command: run worker
    image: 447888000816.dkr.ecr.us-east-1.amazonaws.com/sentry
    restart: always
    links:
      - redis
      - postgres
      - memcached
    environment:
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
    env_file:
      - ./env
    volumes:
      - /data/sentry
    depends_on:
      - postgres
      - redis
      - memcached
